In [1]:
from pandas import Series, DataFrame
import pandas as pd

In [2]:
obj = Series([4,7, -5, 3])

In [3]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [4]:
obj.values

array([ 4,  7, -5,  3])

In [5]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])

In [6]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [7]:
obj2.index

Index([u'd', u'b', u'a', u'c'], dtype='object')

In [8]:
obj2['a']

-5

In [9]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [10]:
obj2['d']=6

In [11]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [13]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [14]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [15]:
'b' in obj2

True

In [16]:
'e' in obj2

False

In [17]:
sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000,'Utah':5000}

In [18]:
obj3=Series(sdata)

In [19]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [20]:
states = ['California','Ohio','Oregon','Texas']

In [21]:
obj4=Series(sdata,index=states)

In [22]:
obj4

California      NaN
Ohio          35000
Oregon        16000
Texas         71000
dtype: float64

In [23]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [24]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [25]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
obj3+obj4

California       NaN
Ohio           70000
Oregon         32000
Texas         142000
Utah             NaN
dtype: float64

In [27]:
obj4.name='population' 
obj4.index.name='state'


In [28]:
obj4

state
California      NaN
Ohio          35000
Oregon        16000
Texas         71000
Name: population, dtype: float64

In [29]:
obj.index=['Bob','Steve','Jeff','Ryan']

In [30]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [31]:
data ={'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}

In [32]:
frame = DataFrame(data)

In [33]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [34]:
DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [35]:
frame2=DataFrame(data,columns=['year','state','pop','debt'],index=['one','two','three','four','five'])

In [36]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [37]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [38]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [39]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan]], dtype=object)

In [40]:
frame2.year.values

array([2000, 2001, 2002, 2001, 2002])

In [41]:
frame2.ix['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [42]:
frame2['debt']=16.5

In [43]:
frame2['debt']=np.arange(5.)

In [44]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [45]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [46]:
frame2['debt']=val

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [48]:
frame2['eastern']=frame2.state=='Ohio'

In [49]:
del frame2['eastern']

In [50]:
frame2.columns

Index([u'year', u'state', u'pop', u'debt'], dtype='object')

In [51]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [52]:
frame3=DataFrame(pop)
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [53]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [54]:
pdata={'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [55]:
DataFrame(pdata)

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [56]:
frame3.index.name='year';frame3.columns.name='state'

In [57]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [58]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [59]:
frame3.values[0]

array([ nan,  1.5])

In [60]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [61]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [62]:
obj=Series(range(3),index=['a','b','c'])
index=obj.index

In [63]:
index

Index([u'a', u'b', u'c'], dtype='object')

In [64]:
index[1:]

Index([u'b', u'c'], dtype='object')

In [65]:
index=pd.Index(np.arange(3))
obj2=Series([1.5,-2.5,0],index=index)

In [66]:
obj2.index is index

True

In [67]:
'Ohio' in frame3.columns

True

In [68]:
obj= Series([4.5,7.2,-5.3,3.6],index=['d','b','a','c'])

In [69]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [70]:
obj2=obj.reindex(['a','b','c','d','e'])

In [71]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [72]:
obj3=Series(['blue','purple','yellow'],index=[0,2,4])

In [73]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [74]:
frame=DataFrame(np.arange(9.).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [75]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [76]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [77]:
frame2=frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a     0      1           2
b   NaN    NaN         NaN
c     3      4           5
d     6      7           8

In [78]:
states =['Texas','Utah','California']

In [79]:
frame.ix[['a','b','c','d'],states]

Texas  Utah  California
a      1   NaN           2
b    NaN   NaN         NaN
c      4   NaN           5
d      7   NaN           8

In [80]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [81]:
new_obj=obj.drop('c')

In [82]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: float64

In [83]:
new_obj

a    0
b    1
d    3
e    4
dtype: float64

In [84]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: float64

In [85]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York',],columns=['one','two','three','four'])

In [86]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [87]:
data.drop('New York',axis=0)

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11

In [88]:
type(obj)

pandas.core.series.Series

In [89]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: float64

In [90]:
obj[1]

1.0

In [91]:
obj[2:4]

c    2
d    3
dtype: float64

In [92]:
obj[['b','a','d']]

b    1
a    0
d    3
dtype: float64

In [93]:
obj['b':'c']

b    1
c    2
dtype: float64

In [94]:
obj['b':'c']=5

In [95]:
obj

a    0
b    5
c    5
d    3
e    4
dtype: float64

In [96]:
data[data['three']<5]

one  two  three  four
Ohio    0    1      2     3

In [97]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data.ix['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [99]:
s1 = Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])

In [100]:
s2 = Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [101]:
s1,s2

(a    7.3
 c   -2.5
 d    3.4
 e    1.5
 dtype: float64, a   -2.1
 c    3.6
 e   -1.5
 f    4.0
 g    3.1
 dtype: float64)

In [102]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [103]:
df1= DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [104]:
df2= DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [105]:
df1+df2

b   c   d   e
Colorado NaN NaN NaN NaN
Ohio       3 NaN   6 NaN
Oregon   NaN NaN NaN NaN
Texas      9 NaN  12 NaN
Utah     NaN NaN NaN NaN

In [106]:
df1.add(df2,fill_value=0)

b   c   d   e
Colorado  6   7   8 NaN
Ohio      3   1   6   5
Oregon    9 NaN  10  11
Texas     9   4  12   8
Utah      0 NaN   1   2

In [107]:
df1.reindex(columns=df2.columns,fill_value=0)

b  d  e
Ohio      0  2  0
Texas     3  5  0
Colorado  6  8  0

In [108]:
arr = np.arange(12.).reshape(3,4)

In [109]:
arr

array([[  0.,   1.,   2.,   3.],
       [  4.,   5.,   6.,   7.],
       [  8.,   9.,  10.,  11.]])

In [110]:
arr[0]

array([ 0.,  1.,  2.,  3.])

In [111]:
arr - arr[0]

array([[ 0.,  0.,  0.,  0.],
       [ 4.,  4.,  4.,  4.],
       [ 8.,  8.,  8.,  8.]])

In [112]:
frame = df2

In [113]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [114]:
series = frame.ix[0]

In [115]:
series

b    0
d    1
e    2
Name: Utah, dtype: float64

In [116]:
frame - series

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [117]:
sample = pd.read_csv('/Users/linwood/Documents/DataSets/CitiTrans.csv', parse_dates='Date')

In [118]:
series2 = Series(range(3),index=['b','e','f'])

In [119]:
frame + series2

b   d   e   f
Utah    0 NaN   3 NaN
Ohio    3 NaN   6 NaN
Texas   6 NaN   9 NaN
Oregon  9 NaN  12 NaN

In [120]:
series2

b    0
e    1
f    2
dtype: int64

In [121]:
series3=frame['d']

In [122]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: float64

In [123]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11